# Generated by Django 3.0.5 on 2020-04-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='resiver',
            new_name='receiver',
        ),
    ]
