# Generated by Django 3.0.5 on 2020-04-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('debts', '0002_auto_20200429_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profiles.UserProfile'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='profiles.UserProfile'),
        ),
    ]
