# Generated by Django 3.0.5 on 2020-05-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_auto_20200429_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='last_update_timestamp',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='timestamp',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
